[[constraint]]
  name = "github.com/AlecAivazis/survey"
  version = "1.4.1"

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/tcnksm/go-gitconfig"
  version = "0.1.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "=4.0.0-rc15"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/rhysd/go-github-selfupdate"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mpppk/gitany"
  version = "0.0.3"
