defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/mpppk/hlb

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make setup
      - run: make deps
      - run: make build
      - run: make test
      - run: make codecov

  release:
    <<: *defaults
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - test
